server:
  port: 8081
  servlet:
    context-path: /

project:
  version: V1.004
#http
http:
  encoding:
    charset: UTF-8
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  default-property-inclusion: non_null

spring:
  profiles:
    active: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&serverTimezone=UTC
    username: root
    password: root


mybatis:
  mapper-locations: classpath:/mapper/transaction/*.xml
  type-aliases-package: com.common.transaction.entity
  configuration:
    default-statement-timeout: 250000
    log-prefix: mybatis

actor:
  name: member
router:
  prefix:
  name: internal@test.yimq

yimq:
  service:
    uri: http://yimq-svc:7379